# Generated by Django 4.2 on 2023-06-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
